assets/css/register.css, login.php, register.php
Changes:
• register.php - Created registration form
• login.php - Added required attribute to login form and alert message for incorrect login
Added:
• register.css
Screenshot:
=> Registration page

assets/css/style.css, home.php
**### User Dashboard:**
Laptop/Desktop View: 
Small Devices View:
=> User Dashboard

assets/css/home.css, home.php
=> User Dashboard Budget Tracker

assets/css/settings.css, settings.php
=> Settings Allign

home.php
=> Modal for Deletion and Add Category

home.php
Add profile dropdown with settings and logout
=> [FE] Add profile dropdown with settings and logout

admin/index.php, admin/setting.php, admin/settings.php
=> [FE] Website Settings section

admin/categories.php, admin/index.php
[FE] Admin | Manage categories ### Page
**Large Devices:**
**Small Devices:**
=> [FE] Admin | Manage categories Page

admin/view.php
**Laptop Desktop View:** 
**Small Devices View:**
=> [FE] Admin | Manage Users | View Page

admin/categories.php, admin/index.php, admin/settings.php, admin/users.php, admin/view.php
• Created users.php
• Linked sidebar navigation to users page
**Screenshot:**
=> [FE] Manage Users Page for the Admin Side

admin/view.php
=> [FE] Added back to user's page

admin/settings.php
=> [FE] Modal upload Settings

home.php
=> [FE] - Add New Transaction Modal 

assets/css/style.css, home.php
• Changed button hover color
• Adjusted column breakpoints and media query for design responsiveness
• Aligned section headings
=> [FE] Adjust UI elements in home page

home.php
=> [FE] - Edit Transaction Modal 

home.php
Added Delete Transaction Modal
=> [FE] - Delete Transaction Modal

home.php
- Added a Delete Modal in Danger Zone
Desktop View:
Mobile View:
=> [FE] Delete Monthly Transaction Modal for the User Dashboard Danger Zone Feature

settings.php
- Upload Profile Picture Modal 
Desktop View:
Mobile View:
=> [FE] - Upload Profile Picture Modal for the User Settings Feature

home.php
-Added back the Delete Transaction Modal for the User Dashboard Transaction Section
=> [FE] Added Delete Monthly Transaction Modal

assets/php/classes.php, assets/shared/navbar.php, home.php
**Yearly/Monthly Finance Report**
- Added category type to see report per category (income, expense, savings)
=> [BE] Yearly Finance Report

assets/shared/navbar.php
Display different navbar links based on the current page
=> [BE] Display different navbar links based on the current page

admin/categories.php
-Added the Edit Category Modal in the admin categories.php
Desktop View:
Mobile View:
=> [FE] - Edit Category Modal for the Manage Categories Feature

admin/categories.php
- Added a modal for the Delete Category in categories.php
Desktop View:
Mobile View:
=> [FE] - Delete Category Modal for the Manage Categories Feature

home.php
**User Dashboard View and Edit User Categories**
=> [BE] User Dashboard View and Edit User Categories

assets/php/functions.php, home.php
Modified
- home.php
- functions.php
=> [BE] - Implementing Functionality to the Back-End of the User Dashboard Overiew Homepage

admin/index.php, assets/css/style.css
- Added the Admin Greetings and the card for the User Statistics
Desktop View:
Mobile View:
=> [FE] - Creation of the Admin Dashboard "Hello Admin!" and User Statistics

admin/settings.php, assets/css/style.css
-Added the Form for Change Username and Change Password for the Admin Settings
Desktop View:
Mobile View:
=> [FE] - Creation of the Account Settings Change Username and Change Password Section for the Admin Settings Page

home.php
-Added the Save Modal for the User Dashboard Category Section
Desktop View:
Mobile View:
=> [FE] - Creation of the Save Modal for the User Dashboard  Category Edit Form

home.php
=> [BE] Implementing Functionality to the Back-End of the User Dashboard Add Transaction History  #57

admin/settings.php, home.php
- refresh function for the home.php page to make sure the saved edit category will reflect
- modified and updated the change logo modal for admin settings
Desktop View:
Mobile View:
=> [FE] - Addition of the Refresh Function for the Category Edit Modal & Modification of Change Logo Modal

assets/php/classes.php, home.php
**Biggest Transaction Feature**
Put on hold backend functionality for the delete month feature as it is subject to changes
=> [BE] Biggest Transaction Feature

admin/index.php, admin/settings.php, assets/css/sidebar.css
=> [FE]-Enhance the Admin dashboard and also changing the BG of dashboard and settings

settings.php
=> [FE]-users settings Delete the phone number in layout box

admin/settings.php, assets/css/style.css
=> Revisions on the Account Settings Change Username and Change Password Section

home.php
=> [BE] - Implementing Functionality to the Back-End of the User Dashboard Add and Delete Categories

assets/php/functions.php, budget-tracker.php, connect.php, home.php
Modified files:
- home.php
- functions.php
Created files:
- budget-tracker.php
=> [BE] - Implementing Functionality to the Back-End of the User Dashboard Budget Tracker Section

assets/php/classes.php, assets/php/functions.php, assets/php/modals/transaction_modals.php, home.php
**Modified:**
- home.php
• Implemented edit and delete functions for transaction history
• Created a function for filtering category dropdown when choosing a type, and automatically selecting type when choosing a category
• Created a function to check if amount input is valid
- classes.php
• Added functions for editing and deleting transactions
- functions.php
• Added functions for showing type and category dropdowns
**New:**
- transaction_modals.php
• Modularized modals in transaction table
**Screenshots:**
Edit:
Delete:
=> [BE] Implementing Functionality to the Back-End of the User Dashboard Edit and Delete Transaction History

admin/categories.php, admin/users.php, admin/view.php, assets/php/classes.php
**Admin | Manage Categories | View:**
**Admin | Manage Categories | Create:**
**Admin | Manage Categories | Edit:**
**Admin | Manage Categories | Delete:**
**Admin | Manage Categories | User Specific List of Categories:**
=> [BE] Admin | Manage Categories CRUD and User Specific List of Categories

404.php, admin/index.php
=> [FE]-Admin Dashboard Changing the font and size of a tooltip

assets/php/functions.php, budget-tracker.php
Modified files:
- budget-tracker.php
- functions.php
Changes:
- Added an error handling for newly registered accounts
=> [BE] -  Made some adjustments to User Dashboard Budget Tracker

admin/users.php, assets/php/classes.php
- Created class for users table
**Modified:**
- users.php
- classes.php
**Screenshot:**
=> [BE] Create user class and table for Manage Users Page

PesoBuddy API/batchusers.php, PesoBuddy API/connect.php, PesoBuddy API/users.php
=> PesoBuddy API for users and batch users

admin/index.php, login.php, register.php
=> [BE] - Implementing Functionality to the Back-End of the Admin Dashboard View Report Page

admin/users.php, assets/php/classes.php, assets/php/modals/admin-delete-user.php, connect.php
Modified files:
- users.php
- classes.php
Created files:
-admin-delete-user.php
=> [BE] - Implementing Functionality to the Back-End of the Manage Users Search, Sort By and Delete Button (w/ delete modal) Feature

assets/php/functions.php, budget-tracker.php, home.php
=> [BE] Danger Zone Delete Feature

assets/css/style.css, assets/php/classes.php
Customize scrollbar appearance and adjust layout for responsiveness
=> [FE] Customize scrollbar appearance and adjust layout for responsiveness

assets/php/classes.php, assets/php/modals/transaction_modals.php, home.php, settings.php
**Modified:**
home.php
- Reordered queries and javascript functions
- Updated insert transaction query
- Added comments for readablity
- Added action attributes to forms
- Fixed issue with clicking categories when adding transaction
- Added a function to check amount input in add transaction
settings.php
- Added bootstrap icons css
classes.php
- User class: Set default profile picture if none is provided
=> Refactored code for readability and functionality improvements

assets/php/modals/delete-account-modal.php, settings.php
Modified files:
- settings.php
Created files:
- delete-account-modal.php
WHAT: Move the whole modal to another PHP file that shall now be included in the settings.php
=> [Modularization] Modularize the 'Delete Account' Modal in the User Settings

home.php
Modified
- home.php (removed iframe)
=> [BE] Removed Iframe

login.php, register.php
=> [FE] Adjust UI elements in Login and Registration Pages
